---
- name: initialize machine
  hosts: localhost
  connection: local
  become: true
  roles:
    - yadm
    - zsh
    - virtualbox
    - media
    - vscode
    - doctools
    - browser
    - container
    - citrix
