---
- name: Add strawberry repository from PPA and install its signing key on Ubuntu target
  become: yes
  apt_repository:
    repo: ppa:jonaski/
    state: present
    update_cache: yes

- name: Install strawberry
  become: yes
  apt:
    name: "strawberry"