---
- name: Install yadm
  become: yes
  apt:
    name: "yadm"

- name: Check if .config/yadm/repo.git/ exists
  stat:
    path: "~/.config/yadm/repo.git/"
  register: stat_result

- name: Clone and bootstrap
  command: yadm clone -b {{ yadm_dotfiles_branch }} {{ yadm_dotfiles_repo }} --bootstrap
  when: not stat_result.stat.exists

- name: Fetch new changes
  command: yadm pull
  when: stat_result.stat.exists